src/server/api/controllers/messages-controller.js
src/server/api/routes/messages-router.js

created messages router & controller template

---

src/server/app.js

Removes default authentication for all endpoints.
`/api/documentation` should now work.

Remove default authentication middleware

---

src/server/api/controllers/channels-controller.js
src/server/api/routes/api-router.js
src/server/api/routes/channels-router.js

- [+] I have performed a self-review of my own code
- [+] I have commented my code, particularly in hard-to-understand areas
- [+] I have made corresponding changes to the documentation
- [+] This PR is ready to be merged and not breaking any other functionality

get channels by query and sort

---

src/server/api/routes/channel-members.router.js

made changes to the post api/channel-members documentation.
N/A

implemented channel-members documentation changes

---

src/server/seeds/development/users.js

Created users database seeds #89 

created users database seeds

---

src/server/api/controllers/channels-controller.js
src/server/api/routes/channels-router.js

Created Endpoint: PATCH api/channels/{id} #22 
Api can be tested using postman. Send a PATCH request to endpoint with channel Id:
PATCH /api/channels/8 HTTP/1.1
Host: localhost:5000

created Endpoint: PATCH api/channels/{id}

---

src/server/api/controllers/users-controller.js
src/server/api/routes/users-router.js

Endpoint: PATCH api/users/{id} #31 
Test using swagger at path api/documentation.
curl -X PATCH "http://localhost:3000/api/users/10" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"profileImage\": \"https://generated.photos/vue-static/home/feed/adult.png\", \"userName\": \"Niel\", \"email\": \"niel123@yahoo.com\", \"lastSeen\": \"2020-09-18T09:20:42.554Z\", \"updatedAt\": \"2020-09-18T09:20:42.554Z\"}"

created Endpoint: PATCH api/users/{id}

---

.eslintrc.js

Disable camel case warning in seeds/controllers.

Remove warning in seeds/controllers

---

.eslintrc.js
src/client/components/CreateANewRoomButton/CreateANewRoomButton.css
src/client/components/CreateANewRoomButton/CreateANewRoomButton.js
src/client/components/CreateANewRoomButton/CreateANewRoomButton.stories.js
src/client/components/RoomList/RoomList.css
src/client/components/RoomList/RoomList.js
src/client/components/RoomList/RoomList.stories.js
src/client/components/RoomListOverview/RoomListOverview.css
src/client/components/RoomListOverview/RoomListOverview.js
src/client/components/RoomListOverview/RoomListOverview.stories.js
src/server/api/routes/api-router.js

made a file for my task make new room button.
Fixes #8 
by storybook
this is just a template.
- [ x ] I have performed a self-review of my own code
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [  ] I have made corresponding changes to the documentation
- [ x ] This PR is ready to be merged and not breaking any other functionality

added new file

---

src/server/api/controllers/messages-controller.js

**Description**
created endpoint: patch/api/messages/{id} to edit message, channel_id, user_id and updated_at fields.
**How to test?**
you can test API using postman and sending a patch request to this endpoint:
http://localhost:3000/api/messages/{id}
- [x ] I have commented on my code, particularly in hard-to-understand areas

editMessage for specific id is made

---

src/server/api/controllers/channel-members.controller.js
src/server/api/routes/channel-members.router.js

Endpoint: PATCH api/channel-members/{id} #32 
Test using swagger at path api/documentation. 
curl -X PATCH "http://localhost:3000/api/channel-members/1" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"channelId\": \"3\", \"userId\": \"5\"}"

created Endpoint: PATCH api/channel-members/{id}

---

src/client/components/Fetcher/UserProfileImage.js
src/client/components/Search/Search.js
src/client/components/Search/Search.styles.css

User's profile image 

---

src/server/api/controllers/messages-controller.js
src/server/api/routes/messages-router.js

Fixed issu in channel_messages controller.
http://localhost:3000/api/documentation

 fixed issue in channel_messages controller and added swagger detail

---

src/server/api/controllers/notifications-controller.js
src/server/api/routes/api-router.js
src/server/api/routes/notifications-router.js

- It is a setup for notifications in the backend and created - notifications controller and notifications router files.
- Refer to user story linked here with.
Fixes # 139
- run server
- [ X] I have performed a self-review of my own code
- [X ] I have commented my code, particularly in hard-to-understand areas
- [X ] I have made corresponding changes to the documentation
- [X ] This PR is ready to be merged and not breaking any other functionality

setup for notifications controller & router files

---

src/client/components/MessageForm/SendMessageForm.js
src/client/components/Profile/ProfileDetails.js
src/client/containers/Channel/Channel.js
src/server/api/controllers/users-controller.js
src/server/api/routes/users-router.js

Add story #53 that is Delele user by id

Delete user by id/#53

---

src/client/hooks/useAuthentication.js

implemented the path of user login: redirect/Overview.
Fixes #116 
npm run dev
sign-in and you will be re-directed to the Overview page.
- [*] I have performed a self-review of my own code
- [ *] I have commented my code, particularly in hard-to-understand areas
- [ *] I have made corresponding changes to the documentation
- [*] This PR is ready to be merged and not breaking any other functionality

implemented user login: redirect to /overview

---

src/client/components/Overview/Overview.js
src/client/components/UsersListComponent/UsersList.js
src/client/components/UsersListComponent/UsersList.stories.js
src/client/components/UsersListComponent/UsersListStyle.css
src/client/containers/UserList/UserList.js

attaching list of users to backend. The PR fetch from backend and display the users on the overview page.
Fixes #62 
You can test by going to the endpoint **http://localhost:3000/overview** 

added attach list of users to backed api

---

src/client/App.js
src/server/api/controllers/channel-members.controller.js
src/server/api/controllers/messages-controller.js
src/server/api/routes/channel-members.router.js

This PR fixes some blank spaces and linting errors
N/A
N/A

fixed blank spaces and lint errors

---

src/server/api/routes/channel-members.router.js

Fix build error

---

src/server/api/controllers/channel-members.controller.js

This PR fixes lint errors in channel-members controller.
N/A
N/A

fixed channel members lint errors

---

src/server/api/controllers/notifications-controller.js
src/server/api/routes/notifications-router.js

Delete Notification at end point :storyNo:#142

Delete Notification at end point

---

src/client/containers/UserList/UserList.js

This PR makes some changes to userlist container. I changed the fetch method to useFetch which makes the code more readable and cleaner.
N/A
You can test at **localhost:3000/overview**

made code cleaner with usefetch.

---

src/client/components/CreateANewRoomButton/CreateANewRoomButton.css
src/client/components/CreateANewRoomButton/CreateANewRoomButton.js
src/client/components/CreateANewRoomButton/CreateANewRoomButton.stories.js
src/client/components/RoomList/RoomList.css
src/client/components/RoomList/RoomList.js
src/client/components/RoomList/RoomList.stories.js
src/client/components/RoomListOverview/RoomListOverview.css
src/client/components/RoomListOverview/RoomListOverview.js
src/client/components/RoomListOverview/RoomListOverview.stories.js

We can see the images of the rooms here...so that we can have a visual representation of the room.
Fix #7 
npm run storybook

Added images for rooms#7

---

src/client/components/SearchMessagesWords/SearchMessages.css
src/client/components/SearchMessagesWords/SearchMessages.js
src/client/components/SearchMessagesWords/SearchMessages.stories.js

Search Messages
You can search words (searchTerm) in messages from channel_messages API. 
I tested 1st with github API to search login and bio, then i used the similar syntax only now with a filter method
to filter only the WORDS that INCLUDES the searchTerm that is already in the setSearchResults list ie-(Messages in the Channel_messages table)
- [*] I have performed a self-review of my own code
- [*] I have commented my code, particularly in hard-to-understand areas
- [*] I have made corresponding changes to the documentation
- [*] This PR is ready to be merged and not breaking any other functionality

Search Messages component

---

src/client/components/SignUp/SignUp.css
src/client/components/SignUp/SignUp.js
src/client/components/SignUp/SignUp.stories.js

Style the sign up page mockup 11 #136
check on storybook

created signup page

---

src/client/index.css

These changes were necessary for story #134 
Fixes #174 
I run npm run dev

changes to global styling

---

src/client/components/SignUp/SignUp.js

Fix signup bug #182
Click on sign up and fill the form to sign up

fixed the signup bug

---

src/server/migrations/20200930112056_add_notifications_table.js
src/server/seeds/development/05_notifications.js

#145 completed task
Backend: Setup database migrations and seeds for notification table
I have verified in MySQL and notifications table and data is created after running the migration and seed scripts

#145 Backend: Setup database migrations and seeds for notification

---

src/client/components/ChannelHeadNav/ChannelHeadNav.js
src/client/components/ChannelHeadNav/ChannelHeadNav.style.css

-Add info button to headd nav
-Add a new parameter (channelId) to ChannelHeadNav()
- Edit channel-head-nav CSS file to style the button 
- Edit channel-head-nav CSS file to fix style issues after adding genral css styling 
test it by running storybook
- [* ] I have performed a self-review of my own code

add info button to head nav and eddit head nav css

---

src/client/components/SignUp/SignUp.js
src/server/migrations/20200930112056_add_notifications_table.js
src/server/seeds/development/05_notifications.js

This PR fixes lint errors and blank spaces in some files.
N/A
N/A

fixed lint errors

---

src/client/components/SignUp/SignUp.js
src/client/containers/SignUp/index.js
src/client/firebase/auth.js

- select file to upload profile image when creating a sign up
Fixes #157 
- It can not be really tested before issue #66 is done
once it is done:
- run: npm run dev
- click on sign up and try to select an image to upload

Store images for users #55

---

src/client/components/MessageForm/SendMessageForm.js
src/client/containers/Channel/Channel.js
src/server/api/controllers/messages-controller.js

Fixed the possibility to send messages and render the messages
Go to http://localhost:3000/channel/12 and see if you can see the messages and send messages

Fix send message form

---

src/client/api/getExistingСhannelForUsers.js
src/client/components/Fetcher/Fetcher.js
src/client/components/SearchMessagesWords/SearchMessages.js
src/client/containers/AddNewRoom/AddNewRoom.js
src/client/containers/SignUp/index.js

fixed all non authenticated fetch requests

---

__mocks__/fileMock.js
src/client/containers/Home/Home.test.js

Fix broken tests

---

src/server/migrations/20200925133337_add_unread_table.js
src/server/seeds/development/06_unread.js

created migration and seeds for unread table that can count unread_messages and update it.  
npm run db:setup

 created migration and seed for unread_messages

---

src/client/components/SignUp/SignUp.js
src/server/api/controllers/channels-controller.js
src/server/api/controllers/channels-message-controller.js
src/server/api/routes/api-router.js
src/server/api/routes/channel-members.router.js
src/server/api/routes/channels-message-router.js
src/server/api/routes/messages-router.js

get the last message and the title of the channels, from the recent channels for a specific user that defined in the endpoint. 
Fixes #4 
run "npm run server" and go to "http://localhost:5000/api/channels-message/2"

getting last message of recent channels-backend

---

src/client/components/Profile/ProfileDetails.js
src/client/components/SignUp/SignUp.js
src/client/containers/SignUp/index.js
src/client/firebase/auth.js

Add user name from input, to firebase, to user context, to profile overview
Fixes #93 
- run "npm run dev" and 
- go to [sign up](http://localhost:3000/sign-up) fill up the form
- go to [profile](http://localhost:3000/profile)

getting user name to profile overview

---

src/client/components/MessageForm/SendMessageForm.js

Clear the input in sendMessageForm when a message is sent.
Fixes #212
http://localhost:3000/channel/12

Done clear message#212

---

src/client/App.js
src/client/components/Overview/Overview.js
src/client/components/Overview/Overview.styles.css

I want to work with the logged in user in the overview page and should be able to logout the logged users details (username, email and id).
http://localhost:3000/Overview

Added the story#122

---

src/server/api/routes/users-router.js

This PR fixes swagger documentation errors api/users get with query userName and email
N/A
It can be tested on **http://localhost:3000/api/documentation/#/default/get_users** 

fixed api/users documentation

---

src/client/components/UnreadMessages/CountUnreadMessages.js
src/client/components/UnreadMessages/Unread.style.css
src/client/components/UnreadMessages/UnreadMessages.stories.js
src/client/components/UnreadMessages/UpdateUnreadMessages.js

Components to count and update unread messages based on every single channel and every user  created . 
Needs Axios to be installed 
Components working with providing: id, channelId  and userId  . This ids can come via proms but before that, you can put an id number in the query string place and test the components.

components for counting and updating unread messages created

---

src/server/api/controllers/notifications-controller.js
src/server/api/routes/notifications-router.js
src/server/migrations/20200930112056_add_notifications_table.js
src/server/seeds/development/05_notifications.js

added get endpoint for notifications
http://localhost:3000/api/notifications
http://localhost:3000/api/notifications/:id
http://localhost:3000/api/notifications?has_been_read=false&sort=desc

added get endpoint for notifications

---

src/client/App.js
src/client/components/Overview/Overview.js
src/server/api/controllers/users-controller.js

Now userContext includes data from database
Once we are taking user data from database instead from Firebase I need to overwrite part of #213 which was taking data from Firebase.
Fixes #221 
run "npm run dev" and log user from userContext

User context includes data from database

---

src/client/components/Profile/ProfileDetails.js
src/client/components/SignOut/SignOut.js
src/client/components/SignOut/SignOut.stories.js
src/client/components/SignOut/SignOut.styles.css

Added Signout button to Profile page
http://localhost:3000/profile

added Signout button to Profile page

---

src/client/components/AddPeopleToRoom/AddPeopleToRoom.css
src/client/components/CreateANewRoomButton/CreateANewRoomButton.css
src/client/components/CreateANewRoomButton/CreateANewRoomButton.js
src/client/components/Overview/Overview.js
src/client/components/Profile/Profile.styling.css
src/client/components/Profile/ProfileDetails.js
src/client/components/RoomListOverview/RoomListOverview.css

Remove global styling from the input, button
Change profile page styling
Fixed styling for add new room button

Fix styling

---

src/client/components/LastMessageList/LastMessagesList.js
src/client/components/LastMessageList/LastMessagesList.stories.js
src/client/containers/LastMessagesList/index.js
src/server/api/controllers/channels-message-controller.js

I made the component and container to show the list of last channels' message. 
Fixes #4 
You can run "npm run storybook"

create component and container for last channels message list

---

src/client/components/Search/Search.js

Fixed if condition in Search to "no users found" 
Fixes #267 
by npm run dev

fixed if condition in Search to "no users found"

---

src/client/components/SignIn/SignIn.js
src/client/components/SignIn/SignIn.style.css
src/client/components/SignUp/SignUp.js
src/client/components/SignUp/SignUp.style.css

I fixed the title position on Sign up and Sign in pages
Changed name of CSS file from SignUp.css to SignUp.style.css
Fixes #265 
bu run npm run dev

Fixed position fo Title in Sign-up and Sign-in pages

---

src/server/api/controllers/users-controller.js
src/server/migrations/20201009131401_add_role_column_to_users_table.js
src/server/seeds/development/01_users.js

add "role" column to "users" table
Fixes ##257
run "npm run knex -- migrate:latest "
run "npm run dev" and go to "http://localhost:3000/api/users"

add role column to users table

---

src/server/migrations/20201010010557_add_imageurl_channels.js
src/server/seeds/development/02_channels.js

First I added imageUrl to the backend by creating new migration file in migrations, in that file I given information regarding tables and columns and then in the corresponding seed I made the corresponding changes in the seed and run that seed regarding my task #217.
In this PR I added only imageUrl to the backend later I will add "roomList" to the backend. 
knex migrate: make migration_name
knex migrate: latest
knex migrate:rollback
knex seed:make seed_name
knex seed:run
npm run db:setup
select * from channels

added imageUrl in migrations and run the seed#217

---

src/client/components/AddPeopleToRoom/ChatGroup.js
src/server/api/controllers/channel-members.controller.js

- fix variables name in get  /api/channel-members/:id 
- effected files *ChatGroup.js *channel-members.controller.js

fix get channel-members/:id api

---

src/client/containers/SignIn/index.js
src/client/firebase/auth.js
src/server/api/controllers/users-controller.js
src/server/api/routes/users-router.js

When Firebase user is signed in, but the local database doesn't have it - create a user in local DB.
Try logging in on staging.

Create Firebase user missing in DB

---

src/client/components/Profile/ProfileDetails.js
src/client/containers/Profile/index.js

It just fixes a small detail created after edit profile feat. was merged.
Fixes #282
run "npm run dev" and go profile and see if role is there.

Fixes user role in the Profile details

---

src/client/containers/Channel/Channel.js
src/server/api/controllers/channels-controller.js

Change the default image to imageUrl from the database.

add room image to navigation header

---

public/index.html
src/client/App.js
src/client/components/CreateANewRoomButton/CreateANewRoomButton.js

This PR links the add new room button to the add-people endpoint. 
It also fixes the 500(Internal Server Error).
Fixes #275 
You can test by running **npm run dev** if you're signed in you can click on the **add new room button** to add/delete people when creating a room OR you can just go directly to **localhost:3000/add-people** and do the same.

Link to /add people

---

src/client/components/footerChatProfile/FooterChatProfile.js

Fixed it.  I left Uppercase in NavLink and change to lowercase in div
Fixes #296 
npm tun dev

Fixed an issue

---

src/client/components/ChannelHeadNav/ChannelHeadNav.js
src/client/components/ChannelInformation/ChannelInformation.style.css
src/client/containers/ChannelInformationContainer/ChannelInfo.js

- edit channelInfo to desplay channel titler or secund member name and foto
-  edit channelInformation.css to fix channel foto
- edit channelHeadNav.js and fix the link to about page
- about page not reach
npm run dev    then /channels/1/about
- [ ^*] I have performed a self-review of my own code

fix info bage not open

---

src/client/components/UsersListComponent/UsersList.js

add missed className

---

src/client/components/AddImageToRoom/AddImageToRoom.js
src/client/components/AddNewRoom/RoomForm.js

This is the image component to add to the new room component.
Added Lucy image component in "Room Form" component where we are creating the new room.
localhost:3000/add-people

Image component added to RoomForm

---

src/client/components/UsersListComponent/UsersList.js

PR has already merged but css style in UserList.js(in components)
was wrong. so i put it back to the previous name.
therefore, im making a new PR.
now search result pictures shown in round shape not in square shape.
Fixes #245 
check in Overview page and try search users name.

line 12 class name to user-list and line 17 user-item

---

src/client/components/LastMessageList/LastMessagesList.js
src/client/containers/LastMessagesList/index.js
src/server/api/controllers/channels-message-controller.js

In the list the last conversation in overview page if the message from the current user we will see 'You: ....message text'.
localhost/overview
write messages, add rooms and write here messages

add author of message

---

src/client/App.js
src/client/components/EditChannel/EditRoom.style.css
src/client/components/EditChannel/RoomItemEdit.js
src/client/components/EditChannel/RoomItemView.js
src/client/components/EditChannel/RoomLink.js
src/client/components/EditChannel/RoomList.js
src/client/components/NavigationHeader/NavigationHeader.js
src/client/containers/EditChannel/RoomListsPage.js

I changed former PR(edit-room)due to a lot of merge conflict and added un related lot of files
Fixes # (57)
npm run  dev

edit channel/room added

---

src/client/components/MessageForm/SendMessageForm.css

SendMessageForm component should be displayed at the bottom.
Changed the file "SendMessageForm.css"
localhost:3000/messages

styling sendmessageform

---

src/client/components/footerChatProfile/FooterChatProfile.styles.css

I Changed  paddings of the footer on screens from 750-1700px
Fixes #315
npm run dev

changed  paddings of the footer on screens from 750-1700px

---

src/client/components/EditChannel/EditRoom.style.css
src/client/components/EditChannel/RoomItemEdit.js
src/client/components/EditChannel/RoomItemView.js
src/client/components/EditChannel/RoomLink.js
src/client/components/EditChannel/RoomList.js
src/client/containers/EditChannel/RoomListsPage.js
src/server/api/controllers/channels-controller.js

This PR is for editing room image. Part of task Edit Room(already merged to develop
npm run dev
- [X ] I have performed a self-review of my own code
- [X ] I have commented my code, particularly in hard-to-understand areas
- [X ] I have made corresponding changes to the documentation
- [X ] This PR is ready to be merged and not breaking any other functionality

Room image editing added

---

src/client/api/getExistingСhannelForUsers.js

fixed bugs with an array of existing channels
http://localhost:3000/channels/:channelId

fix exist channel for user

---

src/client/components/Search/Search.styles.css
src/client/components/UsersListComponent/UsersList.js

Added missed classes, fixed styling 
localhost:3000/overview
search

fix styling user search

---

src/client/components/LastMessageList/LastMessagesList.css
src/client/components/Search/Search.styles.css

Added hover to a user in Search (desktop version)
Fixes #327 
npm run dev - in desktop version

Added hover to a user in Search (desktop version)

---

src/client/components/LastMessageList/LastMessagesList.js
src/server/api/controllers/channel-members.controller.js

fix  user information in list of last conversation

---

src/client/App.js
src/client/components/ChannelInformation/ChannelInformation.style.css
src/client/components/ChannelInformation/ChannelInnformation.js
src/client/containers/ChannelInformationContainer/ChannelInfo.js

fix channel about page

---

src/client/components/RoomList/RoomList.css
src/client/components/RoomList/RoomList.js

Fixed title in a room list (overview page)
Fixes #335 
npm run dev

Fixed title in a room list (overview page)

---

src/client/components/Profile/ProfileDetails.js

Tried to fix the profile image update bug. 
***Note: The logic works only when there is an update of profile image along with username or phonenumber.
npm run dev
- [* ] I have performed a self-review of my own code
- [ *] I have commented my code, particularly in hard-to-understand areas
- [* ] I have made corresponding changes to the documentation

fixed the profile-image-update-bug

---

src/client/containers/Home/Home.styles.css

fixed styling
